[package]
name = "bevy-physics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raqote = "0.8.2"
font-kit = "0.11.0"
minifb = "0.24.0"
cgmath = "0.18.0"
rand = "0.8.5"
