[package]
name = "bevy-physics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raqote = "0.8.2"
font-kit = "0.5.0"
minifb = "0.15.3"
cgmath = "0.18.0"
